trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 16.x
    displayName: Install Node.js

  - script: |
      npm i
    displayName: Install dependencies

  - script: |
      npm run lint
    displayName: Lint

  - script: |
      npm run build:browser
      npm run build:node
    displayName: Build

  - script: |
      npm run publish
    displayName: Publish
    env:
      VSCE_PAT: $(VSCE_PAT)
