trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 16.x
    displayName: Install Node.js

  - script: |
      npm i
    displayName: Install dependencies

  - script: |
      npm run lint
    displayName: Lint

  - script: |
      npm run build:browser
      npm run build:node
    displayName: Build

  - bash: |
      sudo npm i -g vsce
      vsce publish -p $VSCE_PAT
    displayName: Publish
    env:
      VSCE_PAT: $(VSCE_PAT)
