trigger:
  tags:
    include:
      - "prod@*"

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 16.x
    displayName: Install Node.js

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Cache npm

  - script: |
      npm ci
    displayName: Install dependencies

  - script: |
      npm run lint
      npm run test
    displayName: Lint & Test

  - script: |
      npm run build
    displayName: Build

  - bash: |
      npx @vscode/vsce@2 publish -p $VSCE_PAT
    displayName: Publish
    env:
      VSCE_PAT: $(VSCE_PAT)
