// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOVQPOOObQQOOOmQPOOOuQPOOQOQPOOO}QQOOO!VQQOOOOQO'#Ca'#CaOmQPOOOuQPOOOpQPOOOxQPOOOOQO-E6_-E6_",
  stateData: "!_~OWOS~OQSOXQOYRO~OSSOXTOYUO~OQVOXSO~OQVOYSO~OSYOXSO~OSZOYSO~O",
  goto: "aUPPPPPVQWQQXRT[WX",
  nodeNames: "⚠ ClassAttributeValue UsedClassName IdAttributeValue UsedIdName",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#a~R^OX}XY!tYZ!tZ]}]^!t^p}pq!tqr}rs#Vsw}wx#[x;'S};'S;=`!n<%lO}R!UWQPSQOX}Z]}^p}qr}sw}x;'S};'S;=`!n<%lO}R!qP;=`<%l}~!ySW~XY!tYZ!t]^!tpq!t~#[OX~~#aOY~",
  tokenizers: [0, 1],
  topRules: {"ClassAttributeValue":[0,1],"IdAttributeValue":[1,3]},
  tokenPrec: 0
})
