// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOVQPOOObQPOOOmQPOOOuQPOOQOQPOOO}QPOOO!VQPOOOOQO'#C`'#C`OmQPOOOuQPOOOpQPOOOxQPOOOOQO-E6^-E6^",
  stateData: "!_~OVOS~OQSOWQOXRO~OQSOWTOXUO~OQVOWSO~OQVOXSO~OQYOWSO~OQZOXSO~O",
  goto: "`TPPPPUQWQQXRT[WX",
  nodeNames: "⚠ UsedClassNames UsedName UsedIdName",
  maxTerm: 9,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#q~RaOX!WXY#OYZ#OZ[!W[]#O]^#O^p!Wpq#Oqr!Wrs#gsw!Wwx#lx#j!W#j#k#O#k;'S!W;'S;=`!x<%lO!W~!]XQ~OX!WZ[!W^p!Wqr!Wsw!Wx#j!W#k;'S!W;'S;=`!x<%lO!W~!{P;=`<%l!W~#TUV~XY#OYZ#O[]#O]^#Opq#O#j#k#O~#lOW~~#qOX~",
  tokenizers: [0],
  topRules: {"UsedClassNames":[0,1],"UsedIdName":[1,3]},
  tokenPrec: 0
})
