// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOVQPOOObQQOOOmQPOOOuQPOOQOQPOOO}QQOOO!VQQOOOOQO'#Ca'#CaOmQPOOOuQPOOOpQPOOOxQPOOOOQO-E6_-E6_",
  stateData: "!_~OWOS~OQSOXQOYRO~OSSOXTOYUO~OQVOXSO~OQVOYSO~OSYOXSO~OSZOYSO~O",
  goto: "aUPPPPPVQWQQXRT[WX",
  nodeNames: "⚠ ClassAttributeValue UsedClassName IdAttributeValue UsedIdName",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#s~RaOX!WXY#QYZ#QZ[!W[]#Q]^#Q^p!Wpq#Qqr!Wrs#isw!Wwx#nx#j!W#j#k#Q#k;'S!W;'S;=`!z<%lO!WR!_XQPSQOX!WZ[!W^p!Wqr!Wsw!Wx#j!W#k;'S!W;'S;=`!z<%lO!WR!}P;=`<%l!W~#VUW~XY#QYZ#Q[]#Q]^#Qpq#Q#j#k#Q~#nOX~~#sOY~",
  tokenizers: [0, 1],
  topRules: {"ClassAttributeValue":[0,1],"IdAttributeValue":[1,3]},
  tokenPrec: 0
})
